### React Distributed Banking Application
### Run this Command on Terminal to Create the Docker Containers
### > docker compose up
version: '3.8'
services:
  ### First Bank - Arequipa
  bank-arequipa:
    container_name: web-arequipa
    image: react-bank:3.0
    restart: unless-stopped
    ports:
      - "3010:3000"
    expose:
      - 3000
    networks:
      - distributed-bank
  ### Second Bank - Lima
  bank-lima:
    container_name: web-lima
    image: react-bank:3.0
    restart: unless-stopped
    ports:
      - "3011:3000"
    expose:
      - 3000
    networks:
      - distributed-bank
  ### Third Bank - Cusco
  bank-cusco:
    container_name: web-cusco
    image: react-bank:3.0
    restart: unless-stopped
    ports:
      - "3012:3000"
    expose:
      - 3000
    networks:
      - distributed-bank
networks:
  distributed-bank:
    name: distributed-bank
