version: '3.8'
services:
  ### PostgreSQL Database for Inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:15.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: ahincho
    ports:
      - "5440:5432"
    expose:
      - 5432
  ### MySQL Database for Orders
  db-orders:
    container_name: db-orders
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: developer
      MYSQL_PASSWORD: ahincho
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    expose:
      - 3306
  ### MariaDB Database for Products
  db-products:
    container_name: db-products
    image: mariadb:11.0.2
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ms_products
      MARIADB_USER: developer
      MARIADB_PASSWORD: ahincho
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3320:3306"
    expose:
      - 3306